source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
xcodeproj '../Project1.xcodeproj'
# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
#Uncomment this line if you're using Swift
 use_frameworks!


target ‘Project1’ do
pod 'Firebase', '>= 2.5.1'


end

target 'Project1Tests' do

end

target 'Project1UITests' do

end

